### PR TITLE
Fix content_type checking bug and use correct check logic

### PR DESCRIPTION
**Pull request by dp6ai**

### CODE REVIEW

**Comment by dp6ai** [comment]
@musaffa There seems to be a circular dependency issue on travis that you may have a better grasp of.
Travis is trying to install file_validators -v '2.0.2' which has 'mime-types', '>= 1.0' in the gemspec but that wont build because it requires ruby > 2.0.

Any idea how to fix that so travis does not pull the 2.0.2 version and just builds the new code base with the ruby version check in the gemspec?

(Apologies for the new PR...)

**Comment by musaffa** [comment]
It's nothing to worry about. :)

This PR's builds aren't failing for mime-type gem. The failures are in active model 3.x. This gem use [Appraisal](https://github.com/thoughtbot/appraisal) to test multiple versions of active model. Use appraisals included in the gem to test in your machine first.

And a minor correction for the conditional:
```ruby
if RUBY_VERSION < '2.0'
  s.add_dependency 'mime-types', ['>= 1.0', '< 3']
else
  s.add_dependency 'mime-types', '>= 1.0'
end
```

**Comment by dp6ai** [comment]
bundle exec appraisal rake is running green on my machine. Thats why I believe the issue is with the Travis build
```
An error occurred while installing
file_validators (2.0.2), and Bundler
cannot continue.
Make sure that `gem install
file_validators -v '2.0.2'` succeeds
before bundling.

```

This will fail because 2.0.2 doesn't have the correct dependency in the gemspec and therefore can never pass.

**Comment by musaffa** [comment]
You can use Gemfile.lock to lock the `mime-type` to version 2.6.2. The appraisal directory should also have lock files.

**Comment by dp6ai** [comment]
All my .lock files are locking mime-types ate 2.6.2 but when Travis tries to build it is also trying to pull 2.0.2

```
file_validators master % cat gemfiles/*.lock|grep mime-types
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
file_validators master % cat Gemfile.lock|grep mime-types
      mime-types (>= 1.0, < 3)
    mime-types (2.6.2)
      mime-types (>= 1.16, < 3.0)
```

but file_validators is being set in the .lock files at 2.0.2 which means it cant build because that version has 'mime-types', '>= 1.0' in its gemspec.

```
file_validators master % cat Gemfile.lock|grep file_val
    file_validators (2.0.2)
  file_validators!
file_validators master % cat gemfiles/*.lock|grep file_val
    file_validators (2.0.2)
  file_validators!
    file_validators (2.0.2)
  file_validators!
    file_validators (2.0.2)
  file_validators!
    file_validators (2.0.2)
  file_validators!
    file_validators (2.0.2)
  file_validators!
    file_validators (2.0.2)
  file_validators!
```

**Comment by musaffa** [comment]
You shouldn't add Gemfile.lock in the gem repository.

**Comment by dp6ai** [comment]
Yeah I know. just thought id see if that sorted the dependency issues. i'm going to roll it out now

**Comment by musaffa** [comment]
Do your appraisal tests pass for ActiveModel 3.x in your machine? Please have a look where the [builds](https://travis-ci.org/musaffa/file_validators/builds/95810865) are failing. They are failing for one test.

**Comment by dp6ai** [comment]
All my tests pass locally.

The link you sent is not the latest build.

Please look at [this build](https://travis-ci.org/musaffa/file_validators/builds/100815331) all the ruby 2.2.2 tests are passing but the 1.9.3 tests all fail

**Comment by musaffa** [comment]
Do you use rvm/rbenv? Can you test for 1.9.3 in your machine as well?

**Comment by dp6ai** [comment]
Im using rbenv and yes i'm running the tests against 1.9.3

```
file_validators master % rbenv versions
  system
* 1.9.3 (set by /work/file_validators/.ruby-version)
  1.9.3-p551
  2.1
  2.1.5
  2.1.6
  2.1.7
  2.2.2
  2.2.3
file_validators master %
```

**Comment by musaffa** [comment]
Ok let me check.

**Comment by musaffa** [comment]
@dp6ai I've removed ruby 1.9.3 from the CI configuration. Now you have to merge the updates from the master.

**Comment by dp6ai** [comment]
@musaffa it looks like we have a passing test suite :+1: 

Its up to you now. I'd probably suggest mentioning in the readme that ruby < 2.0 requires v 2.0.2.

Thanks for your help 

(Those jruby builds take a long time!)

**Comment by musaffa** [comment]
We are almost there.

1) `'lock mime-types for ruby pre 2.0'` commit isn't necessary anymore.
2) There's still a reference of [Paperclip](https://github.com/SohoHouse/file_validators/blob/master/lib/file_validators/validators/file_content_type_validator.rb#L44) in the code.

**Comment by dp6ai** [comment]
@musaffa changes as requested...

**Comment by musaffa** [comment]
Thanks. :heart:

**Comment by musaffa** [comment]
@dp6ai I would love to have another PR. With the logic of media type spoof detection has been moved to the content type detector, [media type spoof detector](https://github.com/musaffa/file_validators/blob/32a1e9ed54b9dd9c315cae7a5b9250ec86844fb7/lib/file_validators/utils/media_type_spoof_detector.rb) looks redundant now. It can be safely removed along with all its references.

1)  There are some useful [specs] (https://github.com/musaffa/file_validators/blob/489e4e23d182526b3acfb0c276e3d13c5f467ac0/spec/lib/file_validators/utils/media_type_spoof_detector_spec.rb) of media type spoof detector which can be merged in this [content_type_detector_spec](https://github.com/musaffa/file_validators/blob/e1a6a2907c73a7666e80f17f8652a888d84e1a00/spec/lib/file_validators/utils/content_type_detector_spec.rb) file. Content type detector may need to be modified to pass these tests.
2) This [comment](https://github.com/musaffa/file_validators/blob/32a1e9ed54b9dd9c315cae7a5b9250ec86844fb7/lib/file_validators/utils/media_type_spoof_detector.rb#L12-L18) should also be transferred to the content type detector. Leave your comments in the code where they deem appropriate.

Thanks.

**Comment by musaffa** [comment]
Along with this PR, a [hardcoded](https://github.com/musaffa/file_validators/blob/master/file_validators.gemspec#L22) of mime-magic dependency has been introduced. It should be made more liberal. A '=>' sign will be more appropriate.

**Comment by dp6ai** [comment]
I’ll try to look at this in the next couple of days...



Patrick Davenport


[cid:image76b33a.JPG@b7ec64d5.49ad4512]<http://www.sohoworks.com/>
Soho House Terms and Conditions apply
On 11 Jan 2016, at 19:04, Ahmad Musaffa <notifications@github.com<mailto:notifications@github.com>> wrote:


Along with this PR, a hardcoded<https://github.com/musaffa/file_validators/blob/master/file_validators.gemspec#L22> of mime-magic dependency has been introduced. It should be made more liberal. A '=>' sign will be more appropriate.

**Comment by musaffa** [comment]
After merge of this PR, the test coverage fell sharply from 95% to 60%.

**Pull request merged**
